ALTER TABLE pastes
ADD COLUMN is_file BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN file_name TEXT,
ADD COLUMN mime_type TEXT,
ADD COLUMN file_size BIGINT,
ADD COLUMN s3_key TEXT,
ALTER COLUMN content DROP NOT NULL;
