services:
  yoru:
    image: yoru-pastebin:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 2  # load balancing target
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      SERVER_PORT: ${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yoru.rule=Host(`paste.alokranjan.me`)"
      - "traefik.http.routers.yoru.entrypoints=websecure"
      - "traefik.http.routers.yoru.tls=true"
      - "traefik.http.routers.yoru.middlewares=security-headers@file"
      - "traefik.http.routers.yoru.service=yoru-svc"
      - "traefik.http.services.yoru-svc.loadbalancer.server.port=${SERVER_PORT}"
    networks:
      - web

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --api.dashboard=false
      - --api.insecure=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic/config.yml:/etc/traefik/dynamic/config.yml
    networks:
      - web

networks:
  web:
    driver: overlay

volumes:
  db_data:
