services:
  yoru-pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      SERVER_PORT: ${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yoru-api.rule=Host(`paste.alokranjan.me`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.yoru-api.entrypoints=websecure"
      - "traefik.http.routers.yoru-api.tls=true"
      - "traefik.http.routers.yoru-api.service=yoru-pastebin"
      - "traefik.http.services.yoru-pastebin.loadbalancer.server.port=${SERVER_PORT}"
      
      - "traefik.http.routers.yoru-read.rule=Host(`paste.alokranjan.me`)"
      - "traefik.http.routers.yoru-read.entrypoints=websecure"
      - "traefik.http.routers.yoru-read.tls=true"
      - "traefik.http.routers.yoru-read.service=yoru-pastebin"
    networks:
      - web

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik-dynamic.yml:/etc/traefik/dynamic/config.yml
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  db_data:
